### ISSUE TITLE
Other Plattforms?

### ISSUE THREAD

**Issue by blaggacao** [synack/docker-rsync#1]
Did you plan to add other plattforms?

Linux has the inotifywait command, where there is a port to windows.

http://linux.die.net/man/1/inotifywait

https://github.com/thekid/inotify-win

**Comment by blaggacao** [comment]
https://godoc.org/golang.org/x/exp/winfsnotify

I found this, too.

**Comment by mattes** [comment]
Windows would be nice. There is no integration planned from my side though.

I am happy to switch to https://github.com/go-fsnotify/fsnotify, if it integrates [FSEvents](https://github.com/go-fsnotify/fsnotify/issues/11) and maybe Windows, too.

**Comment by mattes** [comment]
Not sure if there is a use-case for Linux.

**Comment by blaggacao** [comment]
https://github.com/go-fsnotify/fsnotify/issues/85

**Comment by blaggacao** [comment]
Windows, more or less the implementation I suggested, is already supported... :) damn, if I had some go capabilities I would give it a try..

**Comment by blaggacao** [comment]
@mattes Could you help me get this done on a tentative PR? (I'm not a Go developer, so I can only help kikstart development). Fsnotify project is somewhat sleepy, so I consider it's not worth waiting, Windows beeing the second major usecase for your docker-rsync tool...

**Comment by mattes** [comment]
Closing this in favor of https://github.com/synack/docker-rsync/pull/6
