### ISSUE TITLE
Not working on Go 1.6

### ISSUE THREAD

**Issue by jcsalem** [synack/docker-rsync#20]
The version on homebrew (currently 0.1.1) doesn't support Go 1.6 due to this issue:
   https://github.com/synack/docker-rsync/issues/16

So I tried building it from the master branch.  I downloaded the latest fsevents.  Now `make build` gives this error:
```
$ make build
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
# github.com/synack/docker-rsync
./watch.go:49: event.Flags undefined (type []fsevents.Event has no field or method Flags)
./watch.go:54: event.ID undefined (type []fsevents.Event has no field or method ID)
./watch.go:54: event.Path undefined (type []fsevents.Event has no field or method Path)
godep: go exit status 2
make: *** [build] Error 1
```

Any ideas how to get past this error?

**Comment by 3den** [comment]
@jcsalem  this project is not required, there is a much easier way to sync docker with your local directory https://gist.github.com/3den/2dbebfa2be0846c51a737d595ad362c4

**Comment by dpintats** [comment]
@jcsalem I believe the /Users directory on the Mac localhost is already added as a sharedfolder in Virtualbox, so wouldn't this achieve roughly the same result as what's currently happening? 

Secondly, if it is a virtualbox sharedfolder, then I believe that's using VBoxSF, which has performance issues with sharing large volumes https://github.com/boot2docker/boot2docker/issues/593 

I believe that's the reason for docker-rsync, to circumvent VBoxSF's performance issues with rsync.

**Comment by dpintats** [comment]
Sorry, that was meant for @3den ^

**Comment by dpintats** [comment]
Lastly, I opened up this to update the event handler for fsevents' handling of the EventStream https://github.com/synack/docker-rsync/pull/21

**Comment by 3den** [comment]
@dpintats you can have multiple shared directories on a virtualbox machine, I did not have any performance issue so far. I also wanted to use docker-rsync but it did not work at all...

**Comment by mattes** [comment]
Going to update the brew version soon.

**Comment by jcsalem** [comment]
Thanks!  Just submitted my PR for a --nodelete argument. Hope you'll consider that.
