### ISSUE TITLE
boot2docker or docker-machine?

### ISSUE THREAD

**Issue by krainboltgreene** [synack/docker-rsync#4]
I'm trying to figure out how to use this, but it's a bit confusing.

The readme says this is a drop in for boot2docker, but the usage talks about `docker-machine` which seems like something I won't need? Also, what is `IP`, `PORT`, and `MODULE` in the rsync version? Is that my host machine? `boot2docker-vm`'s IP? The guest machine's IP?

**Comment by mattes** [comment]
The chain is: docker-rsync -> [docker-machine](https://docs.docker.com/machine/drivers/virtualbox/) -> boot2docker. You can either [run `docker-rsync` with `docker-machine`](https://github.com/synack/docker-rsync#usage-with-docker-machine) or talk to a rsync server directly if you decide not to use docker-machine/boot2docker.  [More rsync documentation](http://linux.die.net/man/1/rsync).

**Comment by krainboltgreene** [comment]
So thanks to this I've figured out that docker-machine replaces boot2docker-cli, which makes this whole thing easier to understand.

**Comment by krainboltgreene** [comment]
@mattes Actually one last question: Now that my source is rsync'd to the docker-machine virtualmachine what's the best way to get it into the container, `VOLUME`?

**Comment by mattes** [comment]
Yes. `-v` is what you're looking for. https://docs.docker.com/reference/run/#volume-shared-filesystems
