### ISSUE TITLE
wget: bad address 'repo.tinycorelinux.net'

### ISSUE THREAD

**Issue by stringbeans** [synack/docker-rsync#9]
When I run `docker-rsync default` I get an error. I'm trying to rsync to the default vm created by docker-machine, named `default`

```
Johns-MBP:jsedvisor john$ docker-rsync default
exit status 1
Downloading: rsync.tcz
wget: bad address 'repo.tinycorelinux.net'
md5sum: rsync.tcz.md5.txt: No such file or directory
Error on rsync.tcz
exit status 1
```

**Comment by c4rl** [comment]
This appears to happen when http://tinycorelinux.net/ is offline

**Comment by greggles** [comment]
According to https://twitter.com/SchumacherFM/status/516824398796296192 it might be possible to use a mirror from http://distro.ibiblio.org/tinycorelinux/5.x/x86/

There's not so much feedback from https://twitter.com/tinycorelinux
